### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by t-sin** [t-sin/inquisitor#48]
Now inquisitor is licensed under the MIT license, but is it right? For it I should do two things: survey and decision.

## TODO

- [x] check license
    - [x] original code of Gauche → MIT
    - [x] Masayuki Onjo's portion → [Dual licensed: GPL and BSD 2-clause](http://lispuser.net/files/guess.tar.gz)
    - [x] zqwell's portion → [GPL (v2? v3?)](https://github.com/zqwell/guess/blob/master/guess.asd)
        - [x] libguess? → MIT
- [ ] decide license of inquisitor that is compatible all above

**Comment by ryukinix** [comment]
Any GPL related license of the mentioned projects? That can become quickly cancerous-spreading if it is used. I would like that inquisitor use something like:
+ MIT (like now)
+ BSD
+ Apache

GPLv3 specifically with reciprocity it have a terrible permissive behavior. I don't like it personally. I think the freedom should be about the individual as first-class citizen!

Awesome project, by the way.

**Comment by t-sin** [comment]
The ancestor codes written with Common Lisp are licensed under two license: GPL (I don't know the version) and BSD 2-clause.

In (Common) Lisp world, It seems that projects loaded with Quicklisp are regarded as *derivatives* in terms of GPL, so I want to avoid pure GPL or I prefer to use [LLGPL created by Franz Inc](http://opensource.franz.com/preamble.html).

Hmmm, it's complicated... :thinking:

> Awesome project, by the way.

Anyway, thank you!:wink:

**Comment by t-sin** [comment]
2 years ago...

I must act to this problem but I don't know what can I do. I want to change the license to non-GPL license but (maybe) I can't because I'm not author of character encoding detection parts. I'm not sure about software licensing.

Please tell me what I can do about this.
